library/urls.py
from django.urls import path, include
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='author'),
    path('authors/<int:author_id>', views.author, name='author'),
    path('', RedirectView.as_view(url='library/', permanent=False)),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('search/', views.search, name='search'),
    path('account/', include('django.contrib.auth.urls')),
    # Class based views for BookInstances
    path('my_books/', views.UserBooksListView.as_view(), name='my-books'),
    path('my_books/<uuid:pk>', views.UserBookDetailView.as_view(), name='my-book'),
    path('my_books/create/', views.UserBookCreateView.as_view(), name='create'),
    path('my_books/<uuid:pk>/update', views.UserBookUpdateView.as_view(), name='update'),
    path('my_books/<uuid:pk>/delete', views.UserBookDeleteView.as_view(), name='delete'),
    # Function based views for BookInstances
    path('my_books2/', views.user_books, name='my-books2'),
    path('my_books2/<uuid:instance_id>', views.user_book, name='my-books2'),
    path('my_books2/<uuid:pk>/update2', views.update_book_instance, name='update2'),
    path('my_books2/<uuid:pk>/delete2', views.delete_book_instance, name='delete2'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('my_books/create2/', views.create_new_book_instance, name='create2'),
    # TRANSLATE
    path('i18n/', include('django.conf.urls.i18n')),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
                  path('library/', include('library.urls')),
                  path('admin/', admin.site.urls),
                  path('', RedirectView.as_view(url='library/', permanent=False)),
                  path('tinymce/', include('tinymce.urls')),
              ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

library/models.py
from PIL import Image
from django.db import models
import uuid
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from django.utils.translation import gettext_lazy as _


class Genre(models.Model):
    """For genre table in database"""
    genre_id = models.AutoField(primary_key=True)
    name = models.CharField(_('Name'), max_length=100, help_text=_('Enter type of genre:'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Genre")
        verbose_name_plural = _('Genre')



class Author(models.Model):
    author_id = models.AutoField(primary_key=True)
    first_name = models.CharField('First name', max_length=100)
    last_name = models.CharField('Last name', max_length=100)
    description = HTMLField('Description', help_text='Enter author description:')

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"

    def display_books(self):
        return ', '.join(book.title for book in self.books.all())


class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='books')
    title = models.CharField(_('Title'), max_length=200, help_text="Enter book title:")
    description = models.TextField(_('Description'), max_length=1000, help_text='Enter books description:')
    isbn = models.CharField(
        'ISBN', max_length=13,
        help_text='ISBN nr.: <a href="https://www.isbn-international.org/content/what-isbn">ISBN code</a>'
    )
    genre = models.ManyToManyField(Genre, help_text='Enter books genre: ')
    cover = ResizedImageField(_('Cover'), size=[300, 400], upload_to='covers', null=True)

    def __str__(self):
        return self.title

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all())


class BookInstance(models.Model):
    instance_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique UUID code")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True, related_name='book_instances')
    due_back = models.DateField('', null=True, blank=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('p', 'Processing'),
        ('t', 'Taken'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    book_status = models.CharField(max_length=1, default='a', blank=True, choices=LOAN_STATUS, help_text='Book status')

    @property
    def is_overdue(self):
        if date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.book.title}'


class BookReview(models.Model):
    book_review_id = models.AutoField(primary_key=True)
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True, related_name='reviews')
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Review', max_length=2000)

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = 'Review'
        ordering = ['-date_created']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    photo = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, *args, **kwargs):
        """ Run the usual save function but also resize uploaded photo        """
        super().save(*args, **kwargs)
        img = Image.open(self.photo.path)
        # if img.height > 300 or img.width > 300:
        output_size = (300, 300)
        img.thumbnail(output_size)
        img.save(self.photo.path)

library/forms.py
from django.contrib.auth.models import User

from .models import BookReview, Profile, BookInstance
from django import forms


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer',)
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']


class DateInput(forms.DateInput):
    type = 'datetime-local'


class UserBookCreateForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'reader', 'due_back']
        widgets = {'reader': forms.HiddenInput(), 'due_back': DateInput()}


class CreateBookInstanceForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'due_back']
        widgets = {
            'due_back': forms.DateInput(format='%Y-%m-%d', attrs={
                'type': 'date'
            }),

        }


class EditBookInstanceForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'due_back', 'book_status']

        widgets = {
            'book': forms.HiddenInput,
        }

library/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.core.paginator import Paginator
from .models import Book, BookReview, BookInstance, Author
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from django.utils.translation import gettext as _
from .forms import EditBookInstanceForm, BookReviewForm, UserUpdateForm, ProfileUpdateForm, CreateBookInstanceForm


# Create your views here.
def index(request):
    book_count = Book.objects.all().count()
    book_instance_count = BookInstance.objects.all().count()
    available_books_count = BookInstance.objects.filter(book_status__exact='a').count()
    author_count = Author.objects.all().count()
    number_of_visits = request.session.get('number_of_visits', 1)
    request.session['number_of_visits'] = number_of_visits + 1
    context = {
        'books': book_count,
        'book_instances': book_instance_count,
        'authors': author_count,
        'available': available_books_count,
        'number_of_visits': number_of_visits
    }
    return render(request, "index.html", context)


# def authors(request):
#     authors = Author.objects.all()
#     context = {
#         'authors': authors
#     }
#     return render(request, 'authors.html', context=context)


def authors(request):
    paginator = Paginator(Author.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_authors = paginator.get_page(page_number)
    context = {
        'authors': paged_authors
    }
    return render(request, 'authors.html', context=context)


def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    context = {
        'author': author
    }
    return render(request, 'author.html', context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 2
    # context_object_name = 'my_book_list'
    # def get_queryset(self):
    #     return Book.objects.filter(title__icontains='The')
    template_name = 'book_list.html'


class BookDetailView(FormMixin, generic.DetailView):
    model = Book
    template_name = 'book_detail.html'
    form_class = BookReviewForm

    # Success url
    def get_success_url(self):
        return reverse('book-detail', kwargs={'pk': self.object.book_id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(BookDetailView, self).form_valid(form)


def search(request):
    """
    Simple search. query takes information from search form,
    search_results filters by input text, book title and descriptions.
    Icontains from contains different that icontains is not key sensitive.
    """
    query = request.GET.get('query')
    search_results = Book.objects.filter(
        Q(title__icontains=query) | Q(description__icontains=query) | Q(author__last_name__icontains=query))
    return render(request, 'search.html', {'books': search_results, 'query': query})


# ------------------------------------------- USER BOOK VIEWS ----------------------------------------------------------
class UserBooksListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'user_books.html'
    paginate_by = 100

    def get_queryset(self):
        return BookInstance.objects.filter(reader=self.request.user, book_status__exact='t').order_by('due_back')


@login_required(login_url='login')
def user_books(request):
    user = request.user
    try:
        user_books = BookInstance.objects.filter(reader=request.user).filter(book_status__exact='t').order_by(
            'due_back')
    except BookInstance.DoesNotExist:
        user_books = None
    context = {
        'user': user,
        'user_books': user_books,
    }
    return render(request, 'user_books2.html', context)


@csrf_protect
def register(request):
    if request.method == "POST":
        # taking all values from registration form
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # checking if passwords matches
        if password != password2:
            messages.error(request, _('Password does not match!'))
            return redirect('register')

        # checking if username is not taken
        if User.objects.filter(username=username).exists():
            messages.error(request, _(f'Username {username} is taken! Choose another one'))
            return redirect('register')

        # checking if email is not taken
        if User.objects.filter(email=email).exists():
            messages.error(request, _(f'User with {email} is already registered!'))
            return redirect('register')

        # if everything is good, create new user.
        User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email,
                                 password=password)
        messages.info(request, _(f'User with username {username} registered!'))
        return redirect('login')
    return render(request, 'registration/register.html')


@login_required
def profile(request):
    return render(request, 'profile.html')


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, _(f"Profile updated"))
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)


# --------------------------------------------------- CRUD -------------------------------------------------------------
# ------------------------------------------------- LIST VIEW ----------------------------------------------------------


class UserBookDetailView(LoginRequiredMixin, generic.DetailView):
    model = BookInstance
    template_name = 'user_book.html'


@login_required(login_url='login')
def user_book(request, instance_id):
    try:
        user_taken_book = BookInstance.objects.get(instance_id=instance_id)
    except BookInstance.DoesNotExist:
        user_taken_book = None
    context = {
        'user_taken_book': user_taken_book
    }
    return render(request, 'user_book2.html', context)


# ------------------------------------------------- CREATE VIEW --------------------------------------------------------

class UserBookCreateView(LoginRequiredMixin, generic.CreateView):
    model = BookInstance
    template_name = 'create_user_book.html'
    fields = ['book', 'due_back']
    success_url = '/library/my_books/'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        form.instance.book_status = 't'
        return super().form_valid(form)


"""
4. Pasiziurekit get_or_create metoda prie to pacio (kai darai per query) sito nereiks cia
:param request:
:return:
"""


@login_required(login_url='login')
def create_new_book_instance(request):
    if request.method == 'POST':
        form = CreateBookInstanceForm(data=request.POST)
        if form.is_valid:
            add_user = form.save(False)
            add_user.reader = request.user
            add_user.book_status = 't'
            add_user.save()
            return redirect('/')
    else:
        form = CreateBookInstanceForm()
    context = {
        'form': form
    }
    return render(request, 'create_user_book2.html', context)


# ------------------------------------------------- UPDATE VIEW --------------------------------------------------------

class UserBookUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = BookInstance
    template_name = 'update_book_instance.html'
    fields = ['book', 'due_back', 'book_status']
    success_url = '/library/my_books/'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    def test_func(self):
        book = self.get_object()
        return self.request.user == book.reader


def update_book_instance(request, pk):
    book_instance = BookInstance.objects.get(instance_id=pk)
    if request.method == "POST":
        form = EditBookInstanceForm(data=request.POST, instance=book_instance)
        if form.is_valid:
            change_form = form.save(False)
            change_form.reader = book_instance.reader
            change_form.save()
            return redirect(f'/library/my_books2/{pk}')
    else:
        form = EditBookInstanceForm(instance=book_instance)
    context = {
        'form': form,
    }
    return render(request, 'update_book_instance2.html', context)


# ------------------------------------------------- DELETE VIEW --------------------------------------------------------


class UserBookDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = BookInstance
    success_url = "/library/my_books/"

library/templates/authors.html
{% extends "base.html" %}

{% block content %}
  <h1>Authors</h1>
  <p>Our books authors</p>
  {% for author in authors %}
<li><a href="{% url 'author' author.author_id %}">{{author.first_name}} {{author.last_name}}</a></li>
    {% endfor %}

<div class="container pages">
    <nav aria-label="...">
        {% if authors.has_other_pages %}
            <ul class="pagination pagination-sm">
                {% for i in authors.paginator.page_range %}
                    {% if authors.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>

{% endblock %}

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>


<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                          clip-rule="evenodd"/>
                </svg>
                {{ user.get_username }}</a>
            {%else%}
            {%endif%}

            {% load i18n %}
            <ul class="sidebar-nav">
                <ul>
                    <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
                    <li><a href="{% url 'books' %}">{% trans "All books" %}</a></li>
                    <li><a href="{% url 'author' %}">{% trans "All authors" %}</a></li>
                    <li>
                        <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0 nav-width">
                            <input name="query" class="form-control" type="text" placeholder="{% trans Search %}">
                        </form>
                    </li>
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}"/>
                        <select name="language">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% for lang in LANGUAGES %}
                            <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected"
                                    {% endif %}>
                                {{ lang.1 }} ({{ lang.0 }})
                            </option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="Go"/>
                    </form>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'my-books' %}">{% trans "Book details" %}</a></li>
                    <li><a href="{% url 'my-books2' %}">{% trans "Book details2" %}</a></li>
                    <li><a class="nav-link" href="{% url 'create' %}?next=/library">{% trans "New book" %}</a>
                        <a class="nav-link" href="{% url 'create2' %}?next=/library">{% trans "New book2" %}</a></li>
                    <li><a href="{% url 'logout' %}?next=/library">{% trans "Logout" %}</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}?next={{request.path}}">{% trans "Login" %}</a></li>
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'register' %}">{% trans "Register" %}</a></li>
                    {% else %}
                    {% endif %}
                </ul>
                {% endif %}
                {%endblock%}
            </ul>
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}"
         role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
</div>
</body>
</html>

library/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
 {% load static %}
<h1>{{ book.title }}</h1>

{% if book.cover %}
<img src="{{ book.cover.url }}" style="margin-bottom: 20px;" class="book-cover">
{% else %}
<img src="{% static 'media/covers/no-image.jpg' %}" style="margin-bottom: 20px;" class="book-cover">
{% endif %}
<p><strong>Author:</strong> <a href="{% url 'author' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Description:</strong> {{ book.description }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copy's:</h4>

    {% for copy in book.book_instances.all %}
    <hr>
    <p class="{% if copy.book_status == 'a' %}
      text-success
      {% elif copy.book_status == 'm' %}
      text-danger
      {% else %}text-warning{% endif %}">
        {{ copy.get_book_status_display }}
    </p>
    {% if copy.book_status != 'a' %}
    <p><strong>Will be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p class="text-muted"><strong>Id:</strong> {{ copy.instance_id }}</p>
    {% endfor %}
</div>

<br>
  <h4>Reviews:</h4>
  {% if book.reviews.all %}
    {% for review in book.reviews.all %}
      <hr>
    <img class="rounded-circle" src="{{review.reviewer.profile.photo.url}}" width="15%">
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>Book has no reviews</p>
  {% endif %}

  {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Leave a review:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Submit">
    </form>
  </div>
  {% endif %}
{% endblock %}

library/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}


<h1>{% trans "Library" %}</h1>
{% if user.is_authenticated %}
    <p> {% trans "Welcome back!" %} {{user.username}} </p>
  {% else %}
  <p>Welcome to book heaven!</p>
{%endif%}
  <p>At this time we have:</p>
  <ul>
    <li><strong>{% trans "Books we have:" %}</strong> {{ books }}</li>
    <li><strong>{% trans "Book instance:" %}</strong> {{ book_instances }}</li>
    <li><strong>{% trans "Available books:" %}</strong> {{ available }}</li>
    <li><strong>{% trans "Author:" %}</strong> {{ authors }}</li>
  </ul>
<p>{% trans "You have visited this site" %} {{number_of_visits}} {% trans "times!" %}</p>

{% endblock %}

library/templates/profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.photo.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
    </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

library/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Search by "{{query}}" result:</h1>
  </br>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        <a href="{% url 'book-detail' book.book_id %}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nothing found :(</p>
  {% endif %}

  {% endblock %}

library/templates/update_book_instance.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update book instance</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

library/templates/update_book_instance2.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update book instance</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

library/templates/user_book.html
{% extends "base.html" %}

{% block content %}
    <h1>My taken books:</h1>
    <hr>
        <ul>
        <img class="rounded-circle" src="{{object.reader.profile.photo.url}}">
        <li><strong class="{% if object.is_overdue %}text-danger{% endif %}">Title: {{object.book.title}}</strong></li>
        <li><strong>Return due:</strong> {{object.due_back}}</li>
        <br/>
      </li>
    </ul>
    <li><strong>Return due:</strong> {{object.due_back}}</li>
            {% if object.reader == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'update' object.pk %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'delete' object.pk %}">Delete</a>
            </div>
            {% endif %}
{% endblock %}

library/templates/user_book_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete book</legend>
            <h2>Do you really wannna delete? {{ object.uuid }} {{object.book.title}}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'my-book' object.pk %}">Decline</a>
        </div>
    </form>
    </div>
{% endblock %}

library/templates/user_books.html
{% extends "base.html" %}

{% block content %}

<h1>My taken books list:</h1>
{% if bookinstance_list %}

    <ul>
        {% for bookinstance in bookinstance_list %}
        <img class="rounded-circle" src="{{bookinstance.reader.profile.photo.url}}">
        <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinstance.book.pk %}">{{bookinstance.book.title}}</a> ({{ bookinstance.due_back }})  </li>
        <li><a href="{% url 'my-book' bookinstance.pk %}">Inspect</a></li>
        {% endfor %}
    </ul>


{% else %}
      <p>At this moment you have no booked books.</p>
{% endif %}

{% endblock %}